/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package form;

import db.Database;
import classname.GiangVien;
import exception.KiemTraDuLieu;
import java.awt.Color;
import java.io.IOException;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import manipulatedb.GVController;
import java.util.Random;
import javax.swing.border.TitledBorder;
/**
 *
 * @author Admin
 */
public class GiaoDienGV extends javax.swing.JFrame {
      private String hoTen = "";
      private String maGiangVien = "";
      private int countClicked = 0;
      private GiangVien gv = new GiangVien();
      private String modeTheme = "";
      private Random rd = new Random();
      private static Color color = new Color(0,0,0);
      
    /**
     * Creates new form GiaoDienGV
     */
    public GiaoDienGV() {
        initComponents();
        setLocationRelativeTo(null);
        setTitle("Giảng viên");
        getThongTin();
        thongTinGiangVien();
        lbTenGV.setText(hoTen);
        hienThiThongTin(false);
     
    }
    public void thongTinGiangVien()
    {
        String sql = "SELECT * FROM GIANGVIEN WHERE MaGiangVien = '"+this.maGiangVien+"'";
        try{
            ResultSet rs = Database.getData(sql);
            while(rs.next())
            {
            gv.setMaNhanVien(rs.getString("MaGiangVien"));
            gv.setHoTen(rs.getString("HoTen"));
            gv.getTaiKhoanGV().setTenDangNhap(rs.getString("TaiKhoan"));
            gv.getTaiKhoanGV().setMatKhau(rs.getString("MatKhau"));
            gv.setGioiTinh(rs.getString("GioiTinh"));
            gv.setSoDienThoai(rs.getString("SoDienThoai"));
            gv.setGiangVienNganh(rs.getString("GiangVienNganh"));
            }
        }
        catch(SQLException ex)
        {
            ex.printStackTrace();
             JOptionPane.showMessageDialog(null, "Tải dữ liệu từ CSDL thất bại!", "Thông báo", JOptionPane.WARNING_MESSAGE);
        }
    }
    public void getThongTin()
    {
        this.hoTen = DangNhap.getTenNhanVien();
        this.maGiangVien = DangNhap.getMaNhanVien();
    }
    public void hienThiThongTin(boolean trangThai)
    {
     lbThongTin.setVisible(trangThai);
     lbDangXuat.setVisible(trangThai);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        colorChooser = new javax.swing.JColorChooser();
        btOK = new javax.swing.JButton();
        jFrame2 = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lbHoTen = new javax.swing.JLabel();
        lbGioiTinh = new javax.swing.JLabel();
        lbSoDienThoai = new javax.swing.JLabel();
        lbNganh = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        toggleCongTac = new javax.swing.JToggleButton();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        txtMatKhauCu = new javax.swing.JPasswordField();
        txtMatKhauMoi = new javax.swing.JPasswordField();
        txtXacNhan = new javax.swing.JPasswordField();
        jLabel8 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        panelTong = new javax.swing.JPanel();
        panelCaNhan = new javax.swing.JPanel();
        lbAccount = new javax.swing.JLabel();
        lbTenGV = new javax.swing.JLabel();
        lbDangXuat = new javax.swing.JLabel();
        lbThongTin = new javax.swing.JLabel();
        panelLuaChon = new javax.swing.JPanel();
        lbXemLich = new javax.swing.JLabel();
        lbXemPhong = new javax.swing.JLabel();
        lbDangKyPhong = new javax.swing.JLabel();
        menuBar = new javax.swing.JMenuBar();
        menuModify = new javax.swing.JMenu();
        menuColor = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        lightMode = new javax.swing.JMenuItem();
        darkMode = new javax.swing.JMenuItem();

        colorChooser.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        btOK.setFont(new java.awt.Font("Roboto", 0, 11)); // NOI18N
        btOK.setText("OK");
        btOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btOKActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jFrame1Layout = new javax.swing.GroupLayout(jFrame1.getContentPane());
        jFrame1.getContentPane().setLayout(jFrame1Layout);
        jFrame1Layout.setHorizontalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGroup(jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addComponent(colorChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jFrame1Layout.createSequentialGroup()
                        .addGap(299, 299, 299)
                        .addComponent(btOK, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jFrame1Layout.setVerticalGroup(
            jFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(colorChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 328, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(34, 34, 34)
                .addComponent(btOK, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(26, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Thông tin cá nhân", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel1.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel1.setText("Họ tên");

        jLabel2.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel2.setText("Giới tính");

        jLabel3.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel3.setText("Số điện thoại");

        jLabel4.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel4.setText("Ngành giảng dạy");

        jSeparator1.setForeground(new java.awt.Color(255, 255, 255));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);

        lbHoTen.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        lbHoTen.setForeground(new java.awt.Color(255, 255, 255));

        lbGioiTinh.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        lbGioiTinh.setForeground(new java.awt.Color(255, 255, 255));

        lbSoDienThoai.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        lbSoDienThoai.setForeground(new java.awt.Color(255, 255, 255));

        lbNganh.setFont(new java.awt.Font("Roboto", 0, 16)); // NOI18N
        lbNganh.setForeground(new java.awt.Color(255, 255, 255));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Đổi mật khẩu", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Roboto", 0, 18), new java.awt.Color(255, 255, 255))); // NOI18N

        toggleCongTac.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        toggleCongTac.setText("OFF");
        toggleCongTac.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toggleCongTacActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel5.setText("Mật khẩu cũ");

        jLabel6.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel6.setText("Mật khẩu mới");

        jLabel7.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        jLabel7.setText("Xác nhận mật khẩu");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(jLabel7))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(27, 27, 27)
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        txtMatKhauCu.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        txtMatKhauMoi.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        txtXacNhan.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Preview.png"))); // NOI18N
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtMatKhauCu, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtMatKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(txtXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)))
                .addGap(0, 16, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(8, 8, 8)
                .addComponent(txtMatKhauCu, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtMatKhauMoi, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtXacNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jButton1.setText("OK");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(toggleCongTac))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(10, 10, 10)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(toggleCongTac, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(36, 36, 36))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 7, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lbHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbNganh, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(28, 28, 28)
                                .addComponent(jLabel2)
                                .addGap(27, 27, 27)
                                .addComponent(jLabel3)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel4))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lbHoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lbGioiTinh, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(27, 27, 27)
                                .addComponent(lbSoDienThoai, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(lbNganh, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 7, Short.MAX_VALUE)))
                .addGap(13, 13, 13)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jFrame2Layout = new javax.swing.GroupLayout(jFrame2.getContentPane());
        jFrame2.getContentPane().setLayout(jFrame2Layout);
        jFrame2Layout.setHorizontalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );
        jFrame2Layout.setVerticalGroup(
            jFrame2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jFrame2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lbAccount.setBackground(new java.awt.Color(255, 255, 255));
        lbAccount.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lbAccount.setForeground(new java.awt.Color(255, 255, 255));
        lbAccount.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/Profile3.png"))); // NOI18N
        lbAccount.setToolTipText("");
        lbAccount.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbAccountMouseClicked(evt);
            }
        });

        lbTenGV.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lbTenGV.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);

        lbDangXuat.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lbDangXuat.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbDangXuat.setText("Đăng xuất");
        lbDangXuat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbDangXuatMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lbDangXuatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbDangXuatMouseExited(evt);
            }
        });

        lbThongTin.setFont(new java.awt.Font("Roboto", 0, 14)); // NOI18N
        lbThongTin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lbThongTin.setText("Thông tin cá nhân");
        lbThongTin.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lbThongTinMouseMoved(evt);
            }
        });
        lbThongTin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbThongTinMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbThongTinMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelCaNhanLayout = new javax.swing.GroupLayout(panelCaNhan);
        panelCaNhan.setLayout(panelCaNhanLayout);
        panelCaNhanLayout.setHorizontalGroup(
            panelCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCaNhanLayout.createSequentialGroup()
                .addGroup(panelCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCaNhanLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbTenGV, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbAccount))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelCaNhanLayout.createSequentialGroup()
                        .addGap(0, 86, Short.MAX_VALUE)
                        .addGroup(panelCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbThongTin, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lbDangXuat, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );
        panelCaNhanLayout.setVerticalGroup(
            panelCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCaNhanLayout.createSequentialGroup()
                .addGroup(panelCaNhanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panelCaNhanLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(lbAccount))
                    .addComponent(lbTenGV, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lbThongTin, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbDangXuat, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        lbXemLich.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lbXemLich.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/XemLich.png"))); // NOI18N
        lbXemLich.setText("XEM LỊCH");
        lbXemLich.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lbXemLichMouseMoved(evt);
            }
        });
        lbXemLich.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbXemLichMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbXemLichMouseExited(evt);
            }
        });

        lbXemPhong.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lbXemPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/XemPhong.png"))); // NOI18N
        lbXemPhong.setText("XEM PHÒNG");
        lbXemPhong.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lbXemPhongMouseMoved(evt);
            }
        });
        lbXemPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbXemPhongMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbXemPhongMouseExited(evt);
            }
        });

        lbDangKyPhong.setFont(new java.awt.Font("Roboto", 0, 18)); // NOI18N
        lbDangKyPhong.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/DangKyPhong.png"))); // NOI18N
        lbDangKyPhong.setText("ĐĂNG KÝ PHÒNG");
        lbDangKyPhong.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                lbDangKyPhongMouseMoved(evt);
            }
        });
        lbDangKyPhong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lbDangKyPhongMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lbDangKyPhongMouseExited(evt);
            }
        });

        javax.swing.GroupLayout panelLuaChonLayout = new javax.swing.GroupLayout(panelLuaChon);
        panelLuaChon.setLayout(panelLuaChonLayout);
        panelLuaChonLayout.setHorizontalGroup(
            panelLuaChonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLuaChonLayout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addComponent(lbXemLich, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 74, Short.MAX_VALUE)
                .addComponent(lbXemPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 189, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelLuaChonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lbDangKyPhong, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(143, 143, 143))
        );
        panelLuaChonLayout.setVerticalGroup(
            panelLuaChonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelLuaChonLayout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(panelLuaChonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbXemLich)
                    .addComponent(lbXemPhong))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                .addComponent(lbDangKyPhong)
                .addGap(31, 31, 31))
        );

        javax.swing.GroupLayout panelTongLayout = new javax.swing.GroupLayout(panelTong);
        panelTong.setLayout(panelTongLayout);
        panelTongLayout.setHorizontalGroup(
            panelTongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelTongLayout.createSequentialGroup()
                .addContainerGap(150, Short.MAX_VALUE)
                .addGroup(panelTongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTongLayout.createSequentialGroup()
                        .addComponent(panelLuaChon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(133, 133, 133))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTongLayout.createSequentialGroup()
                        .addComponent(panelCaNhan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(25, 25, 25))))
        );
        panelTongLayout.setVerticalGroup(
            panelTongLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, panelTongLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCaNhan, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelLuaChon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(34, Short.MAX_VALUE))
        );

        menuModify.setText("Edit");
        menuModify.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        menuColor.setText("Color");

        jMenuItem1.setText("Color Chooser");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        menuColor.add(jMenuItem1);

        menuModify.add(menuColor);

        jMenu4.setText("Theme");

        lightMode.setText("Light Mode");
        lightMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lightModeActionPerformed(evt);
            }
        });
        jMenu4.add(lightMode);

        darkMode.setText("Dark Mode");
        darkMode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                darkModeActionPerformed(evt);
            }
        });
        jMenu4.add(darkMode);

        menuModify.add(jMenu4);

        menuBar.add(menuModify);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(panelTong, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(panelTong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lbXemLichMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbXemLichMouseClicked
        // TODO add your handling code here:
        new XemLich().setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_lbXemLichMouseClicked

    private void lbXemPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbXemPhongMouseClicked
        // TODO add your handling code here:
         new XemPhong().setVisible(true);
         this.dispose();
        
    }//GEN-LAST:event_lbXemPhongMouseClicked

    private void lbDangKyPhongMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDangKyPhongMouseClicked
        // TODO add your handling code here:
         new DKPhong().setVisible(true);
         this.dispose();
       
    }//GEN-LAST:event_lbDangKyPhongMouseClicked

    private void lbXemLichMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbXemLichMouseMoved
        // TODO add your handling code here:
        lbXemLich.setForeground(new Color(rd.nextInt(256), rd.nextInt(256), rd.nextInt(256)));
    }//GEN-LAST:event_lbXemLichMouseMoved

    private void lbXemLichMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbXemLichMouseExited
        // TODO add your handling code here:
        if(modeTheme.equals("light") || modeTheme.equals(""))
        {
        lbXemLich.setForeground(Color.BLACK);
        return;
        }
        lbXemLich.setForeground(Color.WHITE);
    }//GEN-LAST:event_lbXemLichMouseExited

    private void lbXemPhongMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbXemPhongMouseMoved
        // TODO add your handling code here:
        lbXemPhong.setForeground(new Color(rd.nextInt(256), rd.nextInt(256), rd.nextInt(256)));
    }//GEN-LAST:event_lbXemPhongMouseMoved

    private void lbXemPhongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbXemPhongMouseExited
        // TODO add your handling code here:
         if(modeTheme.equals("light") || modeTheme.equals(""))
         {
        lbXemPhong.setForeground(Color.BLACK);
        return;
         }
        lbXemPhong.setForeground(Color.WHITE);
    }//GEN-LAST:event_lbXemPhongMouseExited

    private void lbDangKyPhongMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDangKyPhongMouseExited
        // TODO add your handling code here:
         
         if(modeTheme.equals("light") || modeTheme.equals(""))
         {
        lbDangKyPhong.setForeground(Color.BLACK);
        return;
         }
        lbDangKyPhong.setForeground(Color.WHITE);
    }//GEN-LAST:event_lbDangKyPhongMouseExited

    private void lbDangKyPhongMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDangKyPhongMouseMoved
        // TODO add your handling code here:
            lbDangKyPhong.setForeground(new Color(rd.nextInt(256), rd.nextInt(256), rd.nextInt(256)));
    }//GEN-LAST:event_lbDangKyPhongMouseMoved

    private void lbThongTinMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbThongTinMouseMoved
        // TODO add your handling code here:
        lbThongTin.setForeground(new Color(rd.nextInt(256), rd.nextInt(256), rd.nextInt(256)));
    }//GEN-LAST:event_lbThongTinMouseMoved

    private void lbThongTinMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbThongTinMouseExited
        // TODO add your handling code here:
        if(modeTheme.equals("light") || modeTheme.equals(""))
        {
        lbThongTin.setForeground(Color.BLACK);
        return;
        }
        lbThongTin.setForeground(Color.WHITE);
    }//GEN-LAST:event_lbThongTinMouseExited

    private void lbDangXuatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDangXuatMouseEntered
        // TODO add your handling code here:
        lbDangXuat.setForeground(new Color(rd.nextInt(256), rd.nextInt(256), rd.nextInt(256)));
    }//GEN-LAST:event_lbDangXuatMouseEntered

    private void lbDangXuatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDangXuatMouseExited
        // TODO add your handling code here:
     if(modeTheme.equals("light") || modeTheme.equals(""))
     {
        lbDangXuat.setForeground(Color.BLACK);
        return;
     }
        lbDangXuat.setForeground(Color.WHITE);
    }//GEN-LAST:event_lbDangXuatMouseExited

    private void lbAccountMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbAccountMouseClicked
        // TODO add your handling code here:
        countClicked++;
        if(countClicked %2 != 0)
            hienThiThongTin(true);
        else
            hienThiThongTin(false);
    }//GEN-LAST:event_lbAccountMouseClicked

    private void lbDangXuatMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbDangXuatMouseClicked
        // TODO add your handling code here:
        int luaChon = JOptionPane.showConfirmDialog(null, "Bạn chắc chắn muốn thoát?", "Thông báo", JOptionPane.OK_CANCEL_OPTION);
        if(luaChon == JOptionPane.OK_OPTION)
        {
         new StartPage().setVisible(true);
         this.dispose();
        }
    }//GEN-LAST:event_lbDangXuatMouseClicked
    public void theme(String loaiTheme)
    {
        if(loaiTheme.equals("light"))
        {
            color = new Color(255, 255, 255);
            panelTong.setBackground(Color.WHITE);
            panelLuaChon.setBackground(Color.WHITE);
            panelCaNhan.setBackground(Color.WHITE);
            lbAccount.setForeground(Color.BLACK);
            lbDangXuat.setForeground(Color.BLACK);
            lbTenGV.setForeground(Color.BLACK);
            lbThongTin.setForeground(Color.BLACK);
            lbXemLich.setForeground(Color.BLACK);
            lbDangKyPhong.setForeground(Color.BLACK);
            lbXemPhong.setForeground(Color.BLACK);
            
            return;
        }
        if(loaiTheme.equals("dark"))
        {
            color = new Color(0, 0, 0);
            panelTong.setBackground(Color.BLACK);
            panelLuaChon.setBackground(Color.BLACK);
            panelCaNhan.setBackground(Color.BLACK);
            lbAccount.setForeground(Color.WHITE);
            lbDangXuat.setForeground(Color.WHITE);
            lbTenGV.setForeground(Color.WHITE);
            lbThongTin.setForeground(Color.WHITE);
            lbXemLich.setForeground(Color.WHITE);
            lbDangKyPhong.setForeground(Color.WHITE);
            lbXemPhong.setForeground(Color.WHITE);
            return;
        }
        
    }
    public void setBgFrame2()
    {
         if(modeTheme.equals("light"))
        {
            jPanel1.setBackground(Color.WHITE);
            jPanel1.setForeground(Color.WHITE);
            jPanel2.setBackground(Color.WHITE);
            jPanel3.setBackground(Color.WHITE);
            jPanel5.setBackground(Color.WHITE);
            txtMatKhauCu.setBackground(Color.BLACK);
            txtMatKhauMoi.setBackground(Color.BLACK);
            txtXacNhan.setBackground(Color.BLACK);
            txtMatKhauCu.setForeground(Color.WHITE);
            txtMatKhauMoi.setForeground(Color.WHITE);
            txtXacNhan.setForeground(Color.WHITE);
            jLabel1.setForeground(Color.BLACK);
            jLabel2.setForeground(Color.BLACK);
            jLabel3.setForeground(Color.BLACK);
            jLabel4.setForeground(Color.BLACK);
            jLabel5.setForeground(Color.BLACK);
            jLabel6.setForeground(Color.BLACK);
            jLabel7.setForeground(Color.BLACK);
            jLabel8.setForeground(Color.BLACK);
            lbHoTen.setForeground(Color.BLACK);
            lbGioiTinh.setForeground(Color.BLACK);
            lbSoDienThoai.setForeground(Color.BLACK);
            lbNganh.setForeground(Color.BLACK);
            
            return;
        }
        if(modeTheme.equals("dark"))
        {
            jPanel1.setBackground(Color.BLACK);
            jPanel2.setBackground(Color.BLACK);
            jPanel3.setBackground(Color.BLACK);
            jPanel5.setBackground(Color.BLACK);
            txtMatKhauCu.setBackground(Color.WHITE);
            txtMatKhauMoi.setBackground(Color.WHITE);
            txtXacNhan.setBackground(Color.WHITE);
            txtMatKhauCu.setForeground(Color.BLACK);
            txtMatKhauMoi.setForeground(Color.BLACK);
            txtXacNhan.setForeground(Color.BLACK);
             jLabel1.setForeground(Color.WHITE);
            jLabel2.setForeground(Color.WHITE);
            jLabel3.setForeground(Color.WHITE);
            jLabel4.setForeground(Color.WHITE);
            jLabel5.setForeground(Color.WHITE);
            jLabel6.setForeground(Color.WHITE);
            jLabel7.setForeground(Color.WHITE);
            jLabel8.setForeground(Color.WHITE);
            lbHoTen.setForeground(Color.WHITE);
            lbGioiTinh.setForeground(Color.WHITE);
            lbSoDienThoai.setForeground(Color.WHITE);
            lbNganh.setForeground(Color.WHITE);
            return;
        }
            jPanel1.setBackground(color);
            jPanel2.setBackground(color);
            jPanel3.setBackground(color);
            jPanel5.setBackground(color);
            txtMatKhauCu.setBackground(Color.WHITE);
            txtMatKhauMoi.setBackground(Color.WHITE);
            txtXacNhan.setBackground(Color.WHITE);
            txtMatKhauCu.setForeground(Color.BLACK);
            txtMatKhauMoi.setForeground(Color.BLACK);
            txtXacNhan.setForeground(Color.BLACK);
            jLabel1.setForeground(Color.BLACK);
            jLabel2.setForeground(Color.BLACK);
            jLabel3.setForeground(Color.BLACK);
            jLabel4.setForeground(Color.BLACK);
            jLabel5.setForeground(Color.BLACK);
            jLabel6.setForeground(Color.BLACK);
            jLabel7.setForeground(Color.BLACK);
            jLabel8.setForeground(Color.BLACK);
            lbHoTen.setForeground(Color.BLACK);
            lbGioiTinh.setForeground(Color.BLACK);
            lbSoDienThoai.setForeground(Color.BLACK);
            lbNganh.setForeground(Color.BLACK);
   
    }
    private void darkModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_darkModeActionPerformed
        // TODO add your handling code here:
        theme("dark");
        modeTheme = "dark";
        setBgFrame2();
    }//GEN-LAST:event_darkModeActionPerformed

    private void lightModeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lightModeActionPerformed
        // TODO add your handling code here:
        theme("light");
        modeTheme = "light";
        setBgFrame2();
    }//GEN-LAST:event_lightModeActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here
        jFrame1.setSize((int)(this.getSize().getWidth()/1.2), (int)this.getSize().getHeight());
        jFrame1.setLocation((int)(this.getLocation().getX()*1.2), (int)this.getLocation().getY());
        jFrame1.setTitle("Color");
        jFrame1.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    public void setColor(Color color)
    {
         panelTong.setBackground(color);
         panelLuaChon.setBackground(color);
         panelCaNhan.setBackground(color);
    }
    private void btOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btOKActionPerformed
        // TODO add your handling code here:
        jFrame1.dispose();
       color = new Color(0, 0, 0);
       color = colorChooser.getColor();
       if(color.equals(Color.BLACK))
           modeTheme = "dark";
       if(color.equals(Color.WHITE))
           modeTheme = "light";
       modeTheme = "";
       setColor(color);
       setBgFrame2();
    }//GEN-LAST:event_btOKActionPerformed
    public void setThongTin()
    {
        lbHoTen.setText(gv.getHoTen());
        lbGioiTinh.setText(gv.getGioiTinh());
        lbSoDienThoai.setText(gv.getSoDienThoai());
        lbNganh.setText(gv.getGiangVienNganh());
        
    }
    public void doiMatKhau()
    {
        GVController.update_TaiKhoan(gv.getMaNhanVien(), String.valueOf(txtMatKhauMoi.getPassword()));
        JOptionPane.showMessageDialog(null, "Thay đổi mật khẩu thành công", "Thông báo", JOptionPane.INFORMATION_MESSAGE);
    }
    public boolean kiemTraMatKhau() throws KiemTraDuLieu
    {
         if(String.valueOf(txtMatKhauCu.getPassword()).equals(""))
       {
            txtMatKhauCu.requestFocus();
           throw new KiemTraDuLieu("Không được để trống mật khẩu cũ!");
       }
          if(String.valueOf(txtMatKhauMoi.getPassword()).equals(""))
       {
            txtMatKhauMoi.requestFocus();
            throw new KiemTraDuLieu("Không được để trống mật khẩu mới!");
       }
           if(String.valueOf(txtXacNhan.getPassword()).equals(""))
       {
            txtXacNhan.requestFocus();
            throw new KiemTraDuLieu("Không được để trống xác nhận mật khẩu!");
       }
          if(!String.valueOf(txtMatKhauCu.getPassword()).equals(gv.getTaiKhoanGV().getMatKhau()))
       {
           txtMatKhauCu.requestFocus();
           throw new KiemTraDuLieu("Mật khẩu cũ không chính xác!");
       }
          if(String.valueOf(txtMatKhauCu.getPassword()).equals(String.valueOf(txtMatKhauMoi.getPassword())))
        {
            txtMatKhauMoi.requestFocus();
            throw new KiemTraDuLieu("Mật khẩu mới trùng với mật khẩu cũ!");
       }
           if(String.valueOf(txtMatKhauMoi.getPassword()).length() < 6)
       {
           txtMatKhauMoi.requestFocus();
           throw new KiemTraDuLieu("Mật khẩu mới phải từ 6 kí tự trở lên!");
       }
            if(!String.valueOf(txtMatKhauMoi.getPassword()).matches("[a-zA-Z0-9]+"))
       {
           txtMatKhauMoi.requestFocus();
            throw new KiemTraDuLieu("Mật khẩu mới không được chứa khoảng trống hoặc kí tự đặc biệt!");
       }
           if(!String.valueOf(txtMatKhauMoi.getPassword()).equals(String.valueOf(txtXacNhan.getPassword())))
        {
            txtXacNhan.requestFocus();
             throw new KiemTraDuLieu("MXác nhận mật khẩu không trùng với mật khẩu mới!");
       }
           return true;
    }
    public void khoiTaoMatKhau()
    {
        txtMatKhauCu.setEditable(false);
        txtMatKhauMoi.setEditable(false);
        txtXacNhan.setEditable(false);
    }
    public void khoiTaoBanDau()
    {
        toggleCongTac.setText("OFF");
        toggleCongTac.setSelected(false);
        txtMatKhauCu.setText("");
        txtMatKhauMoi.setText("");
        txtXacNhan.setText("");
        txtXacNhan.setEchoChar('*');
        
    }
    private void lbThongTinMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lbThongTinMouseClicked
        // TODO add your handling code here:
        khoiTaoBanDau();
        setThongTin();
        jFrame2.setSize((int)(this.getSize().getWidth()/1.7), (int)(this.getSize().getHeight()*1.2));
        jFrame2.setLocation((int)(this.getLocation().getX()*1.5), (int)this.getLocation().getY());
        jFrame2.setTitle("Thông tin cá nhân");
        jFrame2.setVisible(true);
        khoiTaoMatKhau();
    }//GEN-LAST:event_lbThongTinMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        if(toggleCongTac.getText().equals("ON"))
        {
        try{
        if(kiemTraMatKhau())
        {
            doiMatKhau();
             jFrame2.dispose();
        }
        }
        catch(KiemTraDuLieu ex)
        {
            JOptionPane.showMessageDialog(null, ex.getMessage(), "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        }
        }
        else
            jFrame2.dispose();
       
    }//GEN-LAST:event_jButton1ActionPerformed

    private void toggleCongTacActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toggleCongTacActionPerformed
        // TODO add your handling code here:
        if(toggleCongTac.getText().equals("OFF"))
        {
        toggleCongTac.setText("ON");
        txtMatKhauCu.setEditable(true);
        txtMatKhauMoi.setEditable(true);
        txtXacNhan.setEditable(true);
        txtMatKhauCu.requestFocus();
        return;
        }
        if(toggleCongTac.getText().equals("ON"))
        {
            toggleCongTac.setText("OFF");
            
            khoiTaoMatKhau();
        }
    }//GEN-LAST:event_toggleCongTacActionPerformed

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        countClicked++;
        if(countClicked%2 != 0)
        txtXacNhan.setEchoChar((char)0);
        else
        txtXacNhan.setEchoChar('*');
    }//GEN-LAST:event_jLabel8MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GiaoDienGV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GiaoDienGV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GiaoDienGV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GiaoDienGV.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new GiaoDienGV().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btOK;
    private javax.swing.JColorChooser colorChooser;
    private javax.swing.JMenuItem darkMode;
    private javax.swing.JButton jButton1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel lbAccount;
    private javax.swing.JLabel lbDangKyPhong;
    private javax.swing.JLabel lbDangXuat;
    private javax.swing.JLabel lbGioiTinh;
    private javax.swing.JLabel lbHoTen;
    private javax.swing.JLabel lbNganh;
    private javax.swing.JLabel lbSoDienThoai;
    private javax.swing.JLabel lbTenGV;
    private javax.swing.JLabel lbThongTin;
    private javax.swing.JLabel lbXemLich;
    private javax.swing.JLabel lbXemPhong;
    private javax.swing.JMenuItem lightMode;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenu menuColor;
    private javax.swing.JMenu menuModify;
    private javax.swing.JPanel panelCaNhan;
    private javax.swing.JPanel panelLuaChon;
    private javax.swing.JPanel panelTong;
    private javax.swing.JToggleButton toggleCongTac;
    private javax.swing.JPasswordField txtMatKhauCu;
    private javax.swing.JPasswordField txtMatKhauMoi;
    private javax.swing.JPasswordField txtXacNhan;
    // End of variables declaration//GEN-END:variables
}
